# -*- coding: utf-8 -*-
"""IA - Aula1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OEfdOjlZHoPAqZocAGOW7vkc5SgZcAm2
"""

import numpy as np

class VetorOrdenado:
  
  def __init__(self, capacidade):
    self.capacidade = capacidade
    self.ultima_posicao = -1
    self.valores = np.empty(self.capacidade, dtype=int)

  def imprime(self):
    if self.ultima_posicao == -1:
      print('O vetor está vazio')
    else:
      for i in range(self.ultima_posicao + 1):
        print(i, ' - ', self.valores[i])

  def insere(self, valor):
    if self.ultima_posicao == self.capacidade - 1:
      print('Capacidade máxima atingida')
      return

    self.ultima_posicao += 1
    pos = self.ultima_posicao
    self.valores[pos] = valor
    
    x = self.ultima_posicao
    while x >= 0 and self.valores[x] < self.valores[x-1]:
      aux = self.valores[x]
      self.valores[x] = self.valores[x-1]
      self.valores[x-1] = aux
      x-=1

vetor = VetorOrdenado(10)
vetor.imprime()

vetor.insere(6)
vetor.imprime()

vetor.insere(4)
vetor.imprime()

vetor.insere(3)
vetor.imprime()

vetor.insere(5)
vetor.imprime()

vetor.insere(1)
vetor.imprime()

vetor.insere(8)
vetor.imprime()